---
  name: Validate pull request
  
  on: pull_request

  permissions:
    contents: read
    statuses: write
  
  jobs:
    validate:
      uses: AdobeDocs/commerce-testing/.github/workflows/validate-pr_job.yml@ds_pr-test-wf
