name: Validate pull request

on: pull_request

permissions:
  contents: read
  statuses: write
  pull-requests: read

jobs:
  testing:
    uses: ./.github/workflows/validate-pr_job.yml
    secrets: inherit
