name: Validate pull request

on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  statuses: write
  pull-requests: write
  checks: write
  actions: read

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Event
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "PR number: ${{ github.event.pull_request.number }}"
          echo "PR base ref: ${{ github.event.pull_request.base.ref }}"
          echo "PR head ref: ${{ github.event.pull_request.head.ref }}"
          echo "PR state: ${{ github.event.pull_request.state }}"

  testing:
    needs: debug
    uses: ./.github/workflows/validate-pr_job.yml
    secrets: inherit
    permissions: write-all
