name: Validate pull request

on: pull_request_target

permissions:
  contents: read
  statuses: write
  pull-requests: write
  checks: write
  actions: read

jobs:
  testing:
    uses: ./.github/workflows/validate-pr_job.yml
