---
###########################
###########################
## Pull request testing ##
###########################
###########################
name: Latest Pull Request

# Documentation:
# - Workflow: https://help.github.com/en/articles/workflow-syntax-for-github-actions
# - SuperLinter: https://github.com/github/super-linter
# - Link validation: https://github.com/remarkjs/remark-validate-links

######################################################
# Start the job on a pull request to the main branch #
######################################################
on: pull_request

###############
# Set the Job #
###############
jobs:
  validate:
    # Set the agent to run on
    runs-on: ubuntu-latest

    ############################################
    # Grant status permission for MULTI_STATUS #
    ############################################
    permissions:
      contents: read
      packages: read
      statuses: write

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files
          # within `super-linter`
          fetch-depth: 0
      - run: cat ".github/super-linter.env" >> "$GITHUB_ENV"

      ################################
      # Run Linters against code base #
      ################################
      - name: Lint Code Base
        #
        # Use full version number to avoid cases when a next
        # released version is buggy
        # About slim image: https://github.com/github/super-linter#slim-image
        uses: super-linter/super-linter/slim@v5.4.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_GITHUB_ACTIONS: true
          FILTER_REGEX_EXCLUDE: .git/*

      - name: Setup Node v16 for Yarn v3
        uses: actions/setup-node@v3
        with:
          node-version: '16.15.1' # Current LTS version

      - name: Enable Corepack for Yarn v3
        run: corepack enable

      - name: Install Yarn v3
        uses: borales/actions-yarn@v3
        with:
          cmd: set version stable

      - name: Install dependencies
        uses: borales/actions-yarn@v3
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
        with:
          cmd: install

      - name: Check internal links
        uses: borales/actions-yarn@v3
        with:
          cmd: test

      - name: Build site
        if: ${{ success() }}
        uses: borales/actions-yarn@v3
        with:
          cmd: build
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"
