---
name: Reusable workflow to validate a pull request

on: workflow_call

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Load super-linter configuration
      shell: bash
      run: cat .github/super-linter.env >> "$GITHUB_ENV"

    - name: Lint Code Base with super-linter
      uses: super-linter/super-linter/slim@v7.3.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  remark-test:
    runs-on: ubuntu-latest
    needs: lint-test
    steps:
      - uses: actions/checkout@v4
      - name: Use Setup Node and Install Dependencies Action
        uses: commerce-docs/devsite-install-action@main
        with:
          node-version-file: '.nvmrc'
          cache-dependency-path: 'yarn.lock'

      - name: Run remark checks (see .remarkrc.yml for enabled plugins)
        run: yarn test

  web-link-check:
    runs-on: ubuntu-latest
    needs: remark-test
    steps:
      - uses: actions/checkout@v4
      - name: Check markdown web links
        uses: tcort/github-action-markdown-link-check@v1
        with:
          base-branch: ${{ github.event.pull_request.base.ref }}
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          check-modified-files-only: 'yes'

  build-test:
    runs-on: ubuntu-latest
    needs: web-link-check
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js and install dependencies
        uses: commerce-docs/devsite-install-action@main
        with:
          node-version-file: '.nvmrc'
          cache-dependency-path: 'yarn.lock'

      - name: Build site
        run: yarn build
